/**
 * Type declarations for virtual modules generated by Vite plugins
 */

declare module 'virtual:conductor-pages' {
  export interface PageDefinition {
    name: string
    path: string
    methods: string[]
    config: any
    handler?: any
  }

  export const pages: PageDefinition[]
  export const pagesMap: Map<string, PageDefinition>
}

declare module 'virtual:conductor-docs' {
  export interface DocsDefinition {
    name: string
    content: string
  }

  export const docs: DocsDefinition[]
  export const docsMap: Map<string, DocsDefinition>
}

declare module 'virtual:conductor-agents' {
  export interface AgentDefinition {
    name: string
    config: string
    handler?: () => Promise<any>
  }

  export const agents: AgentDefinition[]
  export const agentsMap: Map<string, AgentDefinition>
}

declare module 'virtual:conductor-ensembles' {
  export interface EnsembleDefinition {
    name: string
    config: string
  }

  export const ensembles: EnsembleDefinition[]
  export const ensemblesMap: Map<string, EnsembleDefinition>
}
