/// <reference types="vite/client" />

/**
 * Virtual module for auto-discovered pages
 * Generated by vite-plugin-page-discovery at build time
 */
declare module 'virtual:conductor-pages' {
  export interface DiscoveredPage {
    /** Page name */
    name: string
    /** Raw YAML config string */
    config: string
    /** Page handler module (if exists) */
    handler?: any
  }

  /** Map of page name to page data */
  export const pagesMap: Map<string, DiscoveredPage>

  /** Array of all discovered pages */
  export const pages: DiscoveredPage[]

  /** Default export (same as pagesMap) */
  export default pagesMap
}
