name: github-pr-analyzer
description: Analyze GitHub pull requests using MCP tools

flow:
  - agent: get-pr
  - agent: list-files
  - agent: get-file-1
  - agent: get-file-2
  - agent: get-file-3
  - agent: analyze
  - agent: post-comment

# Expose this ensemble as an MCP tool for external systems
trigger:
  - type: mcp
    public: false
    auth:
      type: bearer
      secret: ${env.MCP_CLIENT_TOKEN}

# Send notifications when analysis completes
# Note: Webhook URL must be a valid URL, not an env variable placeholder
# notifications:
#   - type: webhook
#     url: https://hooks.slack.com/services/YOUR/WEBHOOK/PATH
#     events:
#       - execution.completed
#       - execution.failed
#     secret: ${env.WEBHOOK_SECRET}
#     retries: 3

agents:
  # Fetch PR data from GitHub MCP server
  - name: get-pr
    operation: tools
    config:
      mcp: github              # MCP server from conductor.config.ts
      tool: get_pull_request   # GitHub MCP tool
      timeout: 10000

  # Get list of changed files
  - name: list-files
    operation: tools
    config:
      mcp: github
      tool: list_pull_request_files
      timeout: 10000

  # Get file contents for review (first 3 files)
  - name: get-file-1
    condition: ${list-files.output.length > 0}
    operation: tools
    config:
      mcp: github
      tool: get_file_contents
      timeout: 10000

  - name: get-file-2
    condition: ${list-files.output.length > 1}
    operation: tools
    config:
      mcp: github
      tool: get_file_contents
      timeout: 10000

  - name: get-file-3
    condition: ${list-files.output.length > 2}
    operation: tools
    config:
      mcp: github
      tool: get_file_contents
      timeout: 10000

  # Analyze PR with AI
  - name: analyze
    operation: think
    config:
      provider: anthropic
      model: claude-sonnet-4
      prompt: |
        # Pull Request Analysis

        ## PR Details
        Title: ${get-pr.output.title}
        Author: ${get-pr.output.user.login}
        State: ${get-pr.output.state}
        Description: ${get-pr.output.body}

        ## Changed Files (${list-files.output.length} files)
        ${list-files.output}

        ## Sample File Contents
        File 1: ${get-file-1.output}
        File 2: ${get-file-2.output}
        File 3: ${get-file-3.output}

        Please provide a comprehensive code review including:
        1. Summary of changes
        2. Code quality assessment
        3. Potential issues or bugs
        4. Security concerns
        5. Performance considerations
        6. Suggestions for improvement
        7. Overall recommendation (Approve, Request Changes, Comment)

        Format your response as JSON with these fields:
        {
          "summary": "Brief summary",
          "quality_score": 0-100,
          "issues": ["issue1", "issue2"],
          "security_concerns": ["concern1"],
          "performance_notes": ["note1"],
          "suggestions": ["suggestion1"],
          "recommendation": "Approve|Request Changes|Comment",
          "review_comment": "Detailed review comment"
        }

  # Post review comment back to GitHub
  - name: post-comment
    condition: ${input.auto_comment === true}
    operation: tools
    config:
      mcp: github
      tool: create_issue_comment
      timeout: 10000

input:
  owner: ""
  repo: ""
  pull_number: 0
  auto_comment: false

output:
  pr_url: ${get-pr.output.html_url}
  pr_title: ${get-pr.output.title}
  pr_author: ${get-pr.output.user.login}
  files_changed: ${list-files.output.length}
  analysis: ${analyze.output}
  review_posted: ${post-comment.executed}
