# Debug Echo Endpoint
#
# Echoes back the request for debugging.
# Returns method, path, headers, query, and body.
# Useful for testing webhook integrations and API clients.

name: debug-echo
version: 1.0.0
description: Echo endpoint that mirrors back the request

trigger:
  - type: http
    path: /debug/echo
    methods: [GET, POST, PUT, PATCH, DELETE]
    public: true

agents:
  - name: build-echo
    operation: code
    config:
      inline: |
        export default async function(input) {
          return {
            request: {
              method: input.method,
              path: input.path,
              query: input.query,
              headers: input.headers,
              body: input.body,
            },
            echoed_at: new Date().toISOString(),
          }
        }

flow:
  - agent: build-echo
    input:
      method: ${{ trigger.method }}
      path: ${{ trigger.path }}
      query: ${{ trigger.query }}
      headers: ${{ trigger.headers }}
      body: ${{ trigger.body }}

output:
  status: 200
  body:
    echo: ${{ agents.build-echo.output }}
