# Debug Info Endpoint
#
# Returns system information for debugging.
# Shows Conductor configuration, available bindings, and runtime info.
#
# ⚠️ PROTECTED: Requires authentication - do NOT make public in production.

name: debug-info
version: 1.0.0
description: System information endpoint (protected)

trigger:
  - type: http
    path: /debug/info
    methods: [GET]
    auth:
      requirement: required
      methods: [bearer, apiKey]

agents:
  - name: inspect
    agent: inspect-context
    input:
      includeEnv: true
      includeAuth: true
      includeHeaders: true
      includeBindings: true

output:
  status: 200
  body:
    conductor:
      name: "Ensemble-Edge Conductor"
      version: "0.4.x"
    runtime: ${{ agents.inspect.output.context }}
