/**
 * Vite Plugin: Auto-Discovery of Pages
 *
 * Scans pages/ directory for page.yaml files and automatically generates
 * imports and registration code via virtual module.
 */

import { Plugin } from 'vite'
import fg from 'fast-glob'
import * as path from 'node:path'
import * as fs from 'node:fs'

const { globSync } = fg

const VIRTUAL_MODULE_ID = 'virtual:conductor-pages'
const RESOLVED_VIRTUAL_MODULE_ID = '\0' + VIRTUAL_MODULE_ID

export interface PageDiscoveryOptions {
  /** Directory to scan for pages (default: 'pages') */
  pagesDir?: string
  /** Page config file name (default: 'page.yaml') */
  configFileName?: string
}

export function pageDiscoveryPlugin(options: PageDiscoveryOptions = {}): Plugin {
  const pagesDir = options.pagesDir || 'pages'
  const configFileName = options.configFileName || 'page.yaml'

  let root: string

  return {
    name: 'conductor:page-discovery',

    configResolved(config) {
      root = config.root
    },

    resolveId(id) {
      if (id === VIRTUAL_MODULE_ID) {
        return RESOLVED_VIRTUAL_MODULE_ID
      }
    },

    load(id) {
      if (id === RESOLVED_VIRTUAL_MODULE_ID) {
        const code = generatePagesModule(root, pagesDir, configFileName)
        return code
      }
    },

    handleHotUpdate({ file, server }) {
      // Watch for changes in pages directory
      const pagesDirPath = path.resolve(root, pagesDir)

      if (file.startsWith(pagesDirPath)) {
        // Invalidate virtual module on any change in pages/
        const module = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_MODULE_ID)
        if (module) {
          server.moduleGraph.invalidateModule(module)
        }

        // Trigger HMR
        server.ws.send({
          type: 'full-reload',
          path: '*',
        })
      }
    },
  }
}

/**
 * Generate the virtual module code with page imports and pagesMap
 */
function generatePagesModule(root: string, pagesDir: string, configFileName: string): string {
  const pagesDirPath = path.resolve(root, pagesDir)

  // Find all page.yaml files
  const configFiles = globSync(`**/${configFileName}`, {
    cwd: pagesDirPath,
    absolute: false,
  })

  if (configFiles.length === 0) {
    // No pages found - return empty module
    return `
// No pages found in ${pagesDir}/
export const pagesMap = new Map();
export const pages = [];
`
  }

  // Generate imports and map entries
  const imports: string[] = []
  const mapEntries: string[] = []
  const pagesList: string[] = []

  configFiles.forEach((configFile, index) => {
    // Extract page directory name (e.g., 'homepage' from 'homepage/page.yaml')
    const pageDir = path.dirname(configFile)
    const pageName = pageDir || `page${index}`

    // Generate safe variable name
    const varName = `page_${pageName.replace(/[^a-zA-Z0-9_]/g, '_')}_${index}`
    const configVarName = `${varName}_config`
    const handlerVarName = `${varName}_handler`

    // Import paths (relative to pages directory)
    const configPath = path.join(pagesDirPath, configFile)
    const handlerPath = path.join(pagesDirPath, pageDir, 'handler.ts')

    // Read config file content directly
    const configContent = fs.readFileSync(configPath, 'utf-8')

    // Check if handler exists
    const handlerExists = fs.existsSync(handlerPath)

    // Import handler if exists (no need to import config - we embed it)
    if (handlerExists) {
      const relativePath = path.relative(root, handlerPath)
      // Normalize to forward slashes for ESM (path.relative uses OS separators)
      const normalizedPath = relativePath.replace(/\\/g, '/')
      // Ensure path starts with ./ for proper module resolution
      const importPath = normalizedPath.startsWith('.') ? normalizedPath : `./${normalizedPath}`
      imports.push(`import * as ${handlerVarName} from '${importPath}'`)
    }

    // Parse name from YAML config
    const nameMatch = configContent.match(/^name:\s*["']?([^"'\n]+)["']?/m)
    const extractedName = nameMatch ? nameMatch[1] : pageName

    // Generate map entry (embed config content as string literal)
    mapEntries.push(`
  ['${extractedName}', {
    name: '${extractedName}',
    config: ${JSON.stringify(configContent)},
    handler: ${handlerExists ? handlerVarName : 'undefined'},
  }]`)

    // Generate pages array entry
    pagesList.push(`{
    name: '${extractedName}',
    config: ${JSON.stringify(configContent)},
    handler: ${handlerExists ? handlerVarName : 'undefined'},
  }`)
  })

  // Generate final module code
  return `
// Auto-generated by vite-plugin-page-discovery
// This module is generated at build time by scanning ${pagesDir}/

${imports.join('\n')}

export const pagesMap = new Map([
${mapEntries.join(',\n')}
]);

export const pages = [
${pagesList.join(',\n')}
];

// Re-export for convenience
export default pagesMap;
`
}
