/**
 * Vite Plugin: Auto-Discovery of Docs
 *
 * Scans docs/ directory for .md files and automatically generates
 * imports and registration code via virtual module.
 *
 * Makes docs/ work as a first-class component directory like prompts/
 */

import { Plugin } from 'vite'
import fg from 'fast-glob'
import * as path from 'node:path'
import * as fs from 'node:fs'

const { globSync } = fg

const VIRTUAL_MODULE_ID = 'virtual:conductor-docs'
const RESOLVED_VIRTUAL_MODULE_ID = '\0' + VIRTUAL_MODULE_ID

export interface DocsDiscoveryOptions {
	/** Directory to scan for docs (default: 'docs') */
	docsDir?: string
	/** File extension to match (default: '.md') */
	fileExtension?: string
}

export function docsDiscoveryPlugin(options: DocsDiscoveryOptions = {}): Plugin {
	const docsDir = options.docsDir || 'docs'
	const fileExtension = options.fileExtension || '.md'

	let root: string

	return {
		name: 'conductor:docs-discovery',

		configResolved(config) {
			root = config.root
		},

		resolveId(id) {
			if (id === VIRTUAL_MODULE_ID) {
				return RESOLVED_VIRTUAL_MODULE_ID
			}
		},

		load(id) {
			if (id === RESOLVED_VIRTUAL_MODULE_ID) {
				const code = generateDocsModule(root, docsDir, fileExtension)
				return code
			}
		},

		handleHotUpdate({ file, server }) {
			// Watch for changes in docs directory
			const docsDirPath = path.resolve(root, docsDir)

			if (file.startsWith(docsDirPath)) {
				// Invalidate virtual module on any change in docs/
				const module = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_MODULE_ID)
				if (module) {
					server.moduleGraph.invalidateModule(module)
				}

				// Trigger HMR
				server.ws.send({
					type: 'full-reload',
					path: '*',
				})
			}
		},
	}
}

/**
 * Generate the virtual module code with docs imports and docsMap
 */
function generateDocsModule(root: string, docsDir: string, fileExtension: string): string {
	const docsDirPath = path.resolve(root, docsDir)

	// Check if docs directory exists
	if (!fs.existsSync(docsDirPath)) {
		return `
// Docs directory not found: ${docsDir}/
export const docsMap = new Map();
export const docs = [];
`
	}

	// Find all .md files
	const docFiles = globSync(`**/*${fileExtension}`, {
		cwd: docsDirPath,
		absolute: false,
	})

	// Filter out README.md (it's meta-documentation)
	const filteredFiles = docFiles.filter((file) => !file.toLowerCase().includes('readme'))

	if (filteredFiles.length === 0) {
		// No docs found - return empty module
		return `
// No markdown files found in ${docsDir}/
export const docsMap = new Map();
export const docs = [];
`
	}

	// Generate imports and map entries
	const imports: string[] = []
	const mapEntries: string[] = []
	const docsList: string[] = []

	filteredFiles.forEach((docFile, index) => {
		// Extract doc name (file name without extension)
		const docName = path.basename(docFile, fileExtension)

		// Generate safe variable name
		const varName = `doc_${docName.replace(/[^a-zA-Z0-9_]/g, '_')}_${index}`

		// Import path (relative to project root)
		const docPath = path.join(docsDirPath, docFile)

		// Read content directly
		const content = fs.readFileSync(docPath, 'utf-8')

		// Generate map entry (embed content as string literal)
		mapEntries.push(`
  ['${docName}', {
    name: '${docName}',
    content: ${JSON.stringify(content)},
  }]`)

		// Generate docs array entry
		docsList.push(`{
    name: '${docName}',
    content: ${JSON.stringify(content)},
  }`)
	})

	// Generate final module code
	return `
// Auto-generated by vite-plugin-docs-discovery
// This module is generated at build time by scanning ${docsDir}/

export const docsMap = new Map([
${mapEntries.join(',\n')}
]);

export const docs = [
${docsList.join(',\n')}
];

// Re-export for convenience
export default docsMap;
`
}
