name: http-greeting
description: Simple HTTP endpoint that returns a JSON greeting

trigger:
  - type: http
    path: /hello/:name
    methods: [GET]
    public: true
    responses:
      json:
        enabled: true

agents:
  - name: greet-user
    operation: code
    config:
      script: scripts/examples/http/greet-user

flow:
  - agent: greet-user

output:
  greeting: ${greet-user.output.greeting}
  timestamp: ${greet-user.output.timestamp}
  message: ${greet-user.output.message}
