name: product-page
operation: page

route:
  path: /product/:id
  methods: [GET]

beforeRender:
  # Fetch product from Payload CMS
  - name: fetch-product
    operation: payload:findById
    config:
      collection: products
      id: "${params.id}"
      depth: 1

  # Validate API key with Unkey
  - name: validate-key
    operation: unkey:validate
    config:
      apiKey: "${query.api_key}"

  # Create record in Attio CRM
  - name: log-view
    operation: attio:createNote
    config:
      parentObject: products
      parentRecordId: "${params.id}"
      title: "Product viewed"
      content: "Product ${fetch-product.name} was viewed by ${validate-key.ownerId}"

component: |
  <div class="product-page">
    <div class="product-hero">
      <img src="{{ fetch-product.image.url }}" alt="{{ fetch-product.name }}">
      <div class="product-info">
        <h1>{{ fetch-product.name }}</h1>
        <p class="price">${{ fetch-product.price }}</p>
        <p class="description">{{ fetch-product.description }}</p>
        <button class="buy-now">Buy Now</button>
      </div>
    </div>
  </div>

head:
  title: "{{ fetch-product.name }} | Shop"
  meta:
    - name: description
      content: "{{ fetch-product.description }}"
    - property: og:title
      content: "{{ fetch-product.name }}"
    - property: og:image
      content: "{{ fetch-product.image.url }}"
